### ISSUE TITLE
Cryptic Error Messages

### ISSUE THREAD

**Issue by bhairavmehta95** [duckietown/aido-protocols#3]
https://challenges.duckietown.org/v4/humans/submissions/2264

I've been struggling with a lot of these types of errors over the last few days, but one of the overarching themes is that it's not very clear to debug some of these new errors. For example, on image preprocessing, I removed the dataclass + preprocess an image, but I'm not sure what's (not) allowed to do. 

Is there a place in the documentation that's basically a absolutely minimal template, where all mandatory code is documented?

**Comment by bhairavmehta95** [comment]
This is the code that errors - it seems like the Docker file is okay, so the error that I'm currently debugging lies somewhere in here.

https://github.com/duckietown/challenge-aido_LF-template-pytorch/blob/aido2-debug/solution.py

**Comment by bhairavmehta95** [comment]
@AndreaCensi this is what I was talking about.

**Comment by AndreaCensi** [comment]
@bhairavmehta95 you should cast to floats here: https://github.com/duckietown/challenge-aido_LF-template-pytorch/blob/dfa4ad8225351ffd50a46080dfcd1678bd1567b5/solution.py#L47

Please tag me on issues / ping me directly.

**Comment by AndreaCensi** [comment]
![image](https://user-images.githubusercontent.com/81052/55752948-785d3e80-5a49-11e9-8696-5e60bc9793d5.png)
